### ISSUE TITLE
Issues with Assigning Date

### ISSUE THREAD

**Issue by zachwhalen** [judell/h_digipo#1]
Hello,

My students and I have been trying out the [Digipo extension](https://chrome.google.com/webstore/detail/digipo/dllkpndfjcodlhlfiiogdedeipjphkgk) and have come across a few problems. I figure this is the best place to report those issues.

Sometimes students will report that "it doesn't work" or other vague things, but there's at least one apparent bug that I've been able to reproduce. I'm not sure if it's context, browser, or URL dependent.

This is the URL where I can recreate this behavior and error:
http://www.dailymail.co.uk/news/article-3895034/She-didn-t-forecast-Weather-presenter-struck-lightning-live-broadcast-bizarre-Halloween-prank.html#annotations:4XusohSDEeeeF3998Y96Tw

Nothing happens when I select "Assign Publication Date", and these errors appear in my javascript console:
````
VM428:1 
Uncaught SyntaxError: Unexpected identifier

assign_pubdate.js:1 
Uncaught ReferenceError: params is not defined
    at assign_pubdate.js:1
(anonymous) @ assign_pubdate.js:1

````

I confirmed that this same student can successfully assign dates on other articles, and I also have tried it in a "clean" Chrome with no other extensions running and got the same error, which leads me to believe its something specific to the dailymail.co.uk. 

Any ideas?

**Comment by judell** [comment]
Hi Zach,

Thanks for the report, I'll take a look. I've actually made a bunch of
progress on the extension's infrastructure -- in the context of some
related extensions I've been building -- so this is a good reminder to roll
those improvements in to the DigiPo variant, at which point if this isn't
already fixed, I'll fix it.

Cheers,

Jon

**Comment by judell** [comment]
Hi Zach,

I've pushed a new version with a number of fixes and improvements, including that one, hope that helps, and please keep me posted on any other issues or questions.

Cheers,

Jon

**Comment by judell** [comment]
There's now also another way to add a date. If you can't find a date that you can select, you can do this:

![image](https://cloud.githubusercontent.com/assets/46509/24513428/0b614930-1526-11e7-86a8-23d4098c89a0.png)

and then this:

![image](https://cloud.githubusercontent.com/assets/46509/24513485/2af88a06-1526-11e7-8620-cae4f3ac874d.png)

**Comment by zachwhalen** [comment]
This looks great. Thanks Jon!

**Comment by judell** [comment]
You're welcome!

So I have a question for you to ponder. Where should you end up when you submit an annotation from the interstitial page? Initially it redirected to the annotation's direct link, which opened the doc to which the annotation was attached and then scrolled to the annotation. Which is the ultimate confirmation that the annotation was successfully added, but was also a fairly heavyweight operation. When your gathering evidence, the less friction of that sort, the better, I think.

Then we tried redirecting to the associated wiki page. That was also rather heavy, especially since it redirected to a new Digipo tab every time (if, like me, your browser is set to follow links into new tabs instead of replace what's in the current tab).

So for now, we just close the tab containing the interstitial page. Which is the ultimate in streamlining, but probably too abrupt. 

Some possibilities;

- A quick confirmation message, maybe even just a JS alert, before closing that tab.

- Scan the open tabs to see if the corresponding Digipo page is open in one of them, and if so, switch to that tab (and then, if possible, close the interstitial tab).

I'm not sure what's best here, so if you have an opinion, I'm all ears.
