### ISSUE TITLE
Chrome Extension not working (404 error)

### ISSUE THREAD

**Issue by zachwhalen** [judell/h_digipo#2]
Hi Jon,

I was attempting to use the Digipo Chrome Extension just now in a screencast for my students, and I found an error when attempting to save an annotation or a date for the timeline. Basically, nothing happens when clicking "go", and in my browser console, I see a 404 error for  https://h.jonudell.info/create, which I also see if I attempt to browse to that page.

Has that page moved?

**Comment by judell** [comment]
Yes, that was an error, sorry, fixed now. For posterity, I've just discovered that endpoint isn't even needed, it's there to work around a limitation of the Hypothesis API, which currently does not support CORS (Cross-Origin Resource Sharing) for POST requests. So I've been sending requests from the extension through a little [proxy](https://github.com/judell/h_cors) that lives at that endpoint. It turns out, though, that the context in which the extension makes that request doesn't trigger the CORS protocol, so the extension can call the Hypothesis API directly. I'll remove the call to the proxy in an update.

Sorry for the hassle, thanks for reporting this. While I've got you, I should mention that Mike Caulfield and I are working toward a new version of the extension that's motivated by the strong desire, on the part of many students, not to use doku wiki, or any wiki, to write their claim evaluations. So we plan to enable them to use Google Docs as a writing tool embedded into the course CMS.

Here's an example of a page in that (simple, homegrown) CMS:

http://www.digipo.io/wiki/articles/Does-Shaq-believe-the-Earth-is-flat.htm

It just pulls in an export from Google Docs, where the writing occurs. As you can see, it has the same footnote behavior as in the wiki, because that only involves recognizing Hypothesis URLs in the HTML extracted from Google.

The next step is to hook the extension up so that it can query the CMS for the set of existing articles, from which we derive the tags that enable the Related Annotations and Timeline features in the current setup.  We also want to empower the extension to be able to create a new investigation page.

I'm interested to know your thoughts on this. If there's a desire to keep using the wiki, the current extension could live on, and could be configurable for some other wiki than the one DigiPo has been using.  In which case the extension would be a separate thing.

Alternatively if there's no attachment to the wiki and the GDoc-based CMS approach seems better, then the current extension could just migrate to that. We don't expect Digipo courses to really get going until the fall, so that'd be the planned timeline.

**Comment by zachwhalen** [comment]
Hi Jon,

Thanks for your quick response and solution. The extension is indeed working as advertised, so I was able to make my demo video for my students.

I had heard something about the possible switch to GDocs, and I agree, it makes sense for many students. That said, I don't think my students had all that much trouble with the wiki, and I do like the wiki myself, but I'm not wedded to it. The CMS presentation clearly looks better, and if we're thinking about these articles in a rhetorical sense, as in something you'd send to your uncle on Facebook when someone mentions a debunked claim, then the CMS version is a much cleaner and familiar, Medium-like presentation that will help.

As far as workflow, the main thing I like about the wiki is the way it insists on accountability, so if a student has to edit someone else's work, they have a responsibility and a text field in which to justify that edit. So long as there's a similar way to keep track of those contributions via the Google Docs method, then it would be an easy switch for me. 

Really, I'm happy to roll with whatever form it takes. I love the project, and my students found it really valuable last semester, so I'll probably keep integrating it into my DGST 101 for the foreseeable future.
